name: Run CI
on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup rust directory in CI environment
        run: rm -vrf /home/runner/.cargo
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - uses: actions/checkout@v2
      - name: Run tests
        run: nix-shell --pure --command "./test.sh"
